# Generated by Django 3.2.8 on 2021-11-08 11:23

import contacts.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('phone_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number must include 5 to 15 digits.', regex='^\\+?\\d{5,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_born', models.DateField(blank=True, validators=[contacts.models.validate_date_born])),
                ('date_added', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 11, 8, 11, 23, 0, 884925, tzinfo=utc))),
                ('action', models.CharField(choices=[('Call', 'Call'), ('Email', 'Email'), ('IM', 'Im')], default='Call', max_length=5)),
                ('result', models.CharField(choices=[('Success', 'Success'), ('Failure', 'Failure')], default='Success', max_length=7)),
                ('comment', models.TextField(blank=True, max_length=150)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
            ],
        ),
    ]
