# Generated by Django 3.2.8 on 2021-10-29 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='date_born',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone_number',
        ),
    ]
