# Generated by Django 3.2.8 on 2021-10-29 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20211029_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Length of number must be between 5 and 15 digits.', regex='^\\+?\\d{5,15}$')]),
        ),
    ]
